# Base configs
baseurl: "https://photos.huuhieu.name.vn"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Steve"
subtitle: "See the world through my eyes!"
author: "Steve"
header:
 title: "Photography"
 subtitle: "by Steve"
footer:
 name: "Hey there, my name is Steve"
 bio: "I am a developer and a tech aficionado from Vietnam. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "fname": "Model: "}, {"tag": "LensModel", "fname:": "Lens: "}, {"tag": "FNumber", "fname": "F"}, {"tag": "ExposureTime", "fname": "Shutter Speed: "}, {"tag": "ISOSpeedRatings", "fname": "ISO "}]'
social_urls:
  instagram: "https://www.instagram.com/nguyenhuuhieu_"
  facebook: "https://www.facebook.com/huuhieu2001"
  github: "https://www.github.com/huuhieu17"
